spring:
  application:
    name: "task-ms"
  datasource:
    url:  jdbc:h2:file:./tasks_data;AUTO_SERVER=TRUE
    username: admin
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 3001